import { Provider } from '@/components/ui/provider';
import './globals.css';
import { Theme } from '@chakra-ui/react';
import Sidebar from '@/layouts/Sidebar';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html suppressHydrationWarning>
            <body>
                <Provider>
                    <Theme appearance="light" minHeight="100vh">
                        <Sidebar />
                        <div className="main">{children}</div>
                    </Theme>
                </Provider>
            </body>
        </html>
    );
}
