import { Provider } from '@/components/ui/provider';
import Header from '@/layouts/Header';
import Sidebar from '@/layouts/Sidebar';
import { Theme } from '@chakra-ui/react';
import 'react-datepicker/dist/react-datepicker.css';
import './globals.css';
import { SWRProvider } from './swr-provider';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html suppressHydrationWarning>
            <body>
                <Provider>
                    <SWRProvider>
                        <Theme appearance="light" minHeight="100vh">
                            <Sidebar />
                            <div className="main">
                                <Header />
                                <div className="content">{children}</div>
                            </div>
                        </Theme>
                    </SWRProvider>
                </Provider>
            </body>
        </html>
    );
}
